apiVersion: 1

groups:
  - orgId: 1
    name: item-service-alerts
    folder: Item Service
    interval: 10s
    rules:
      - uid: app-down
        title: App is down
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: up{job="app"}
              instant: true
              refId: A
            relativeTimeRange:
              from: 300
              to: 0
          - refId: B
            datasourceUid: __expr__
            model:
              type: threshold
              expression: A
              conditions:
                - evaluator:
                    type: lt
                    params:
                      - 1
                  operator:
                    type: and
              refId: B
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "App is down (up{job=\"app\"} == 0 for 5s)"
        noDataState: Alerting
        execErrState: Alerting

      - uid: db-down
        title: Database is down
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: pg_up{job="postgres"}
              instant: true
              refId: A
            relativeTimeRange:
              from: 300
              to: 0
          - refId: B
            datasourceUid: __expr__
            model:
              type: threshold
              expression: A
              conditions:
                - evaluator:
                    type: lt
                    params:
                      - 1
                  operator:
                    type: and
              refId: B
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "Database is down (pg_up{job=\"postgres\"} == 0 for 5s)"
        noDataState: Alerting
        execErrState: Alerting